### ISSUE TITLE
CD releases are not being tagged

### ISSUE THREAD

**Issue by rhys-vdw** [rhys-vdw/ts-auto-guard#109]
We should tag each release commit with its version. This makes it easier for users to find the source and docs, and also will prompt GitHub to include it in [releases](https://github.com/rhys-vdw/ts-auto-guard/releases).

**Comment by 0xorial** [comment]
Strange, from the docs (https://docs.npmjs.com/cli/v6/commands/npm-version) I thought that tag should be created by `npm version` ... or did I misunderstand?..

**Comment by rhys-vdw** [comment]
Yeah I saw that too. Maybe it's not pushing the tags up from the CI process? I believe there's a flag for git push.
