### ISSUE TITLE
Support string names in interfaces

### ISSUE THREAD

**Issue by pikaju** [rhys-vdw/ts-auto-guard#123]
Interfaces defined with string names produce invalid guard files:
```ts
/**
 * Interface representing the payload of a JWT.
 * @see https://tools.ietf.org/html/rfc7519.
 * @see {isJwtPayload} ts-auto-guard:type-guard
 */
export interface JwtPayload extends Record<string, unknown> {
  'iss'?: string;
  'sub'?: string;
  'aud'?: string;
  'exp'?: number;
  'nbf'?: number;
  'iat'?: number;
  'jti'?: string;
}
```
```ts
export function isJwtPayload(obj: any, _argumentName?: string): obj is JwtPayload {
    return (
        (obj !== null &&
            typeof obj === "object" ||
            typeof obj === "function") &&
        (typeof obj.'iss' === "undefined" ||
            typeof obj.'iss' === "string") &&
                (typeof obj.'sub' === "undefined" ||
                    typeof obj.'sub' === "string") &&
                        (typeof obj.'aud' === "undefined" ||
                            typeof obj.'aud' === "string") &&
                                (typeof obj.'exp' === "undefined" ||
                                    typeof obj.'exp' === "number") &&
                                        (typeof obj.'nbf' === "undefined" ||
                                            typeof obj.'nbf' === "number") &&
                                                (typeof obj.'iat' === "undefined" ||
                                                    typeof obj.'iat' === "number") &&
                                                        (typeof obj.'jti' === "undefined" ||
                                                            typeof obj.'jti' === "string")
)
}
```
The code generator should use square brackets, either just for string names or all interface members in general.

**Comment by rhys-vdw** [comment]
Interesting. Can you confirm that you're on latest version? This was meant to be addressed recently <https://github.com/rhys-vdw/ts-auto-guard/blob/a749c59f09fdd00c49db96dd235225fe01f02a59/tests/generate.ts#L174-L198> by #119.

I think this might be as simple as changing [this check](https://github.com/rhys-vdw/ts-auto-guard/blob/a749c59f09fdd00c49db96dd235225fe01f02a59/src/index.ts#L551) to:

```ts
const isIdentifier = propertyName[0] !== '"' && propertyName[0] !== "'"
```

Wanna give it a shot?

**Comment by flixcheck** [comment]
We have the same issue 😕 

These are the types / interfaces:

``` typescript
export enum Language {
    German = "de-DE"
}

/** @see {isStringPerLanguage} ts-auto-guard:type-guard */
export type StringPerLanguage = {
    [key in Language]?: string;
};

```

and this is the output:

``` typescript
export function isStringPerLanguage(obj: any, _argumentName?: string): obj is StringPerLanguage {
    return (
        ((obj !== null && typeof obj === "object") || typeof obj === "function") &&
        (typeof obj.de - DE === "undefined" || typeof obj.de - DE === "string")
    );
}
```

Desired output is:

``` typescript
export function isStringPerLanguage(obj: any, _argumentName?: string): obj is StringPerLanguage {
    return (
        ((obj !== null && typeof obj === "object") || typeof obj === "function") &&
        (typeof obj["de-DE"] === "undefined" || typeof obj["de-DE"] === "string")
    );
}
```

Can we help improve this library or is it just a small fix?

**Comment by rhys-vdw** [comment]
@flixcheck I'm optimistic about the fix I suggested in my previous message (https://github.com/rhys-vdw/ts-auto-guard/issues/123#issuecomment-749313446).  PRs welcome. ❤️

**Comment by rhys-vdw** [comment]
And, if I'm wrong and that doesn't work, there is always @0xorial's more comprehensive fix (#118) that could be revived. We removed it thinking that invalid identifiers would always be quoted by ts-morph, and hence that checking if `fieldName[0]` was a quote would be sufficient. However this enum case may be an exception?

**Comment by flixcheck** [comment]
We found out that the reason is that we are using a `type` instead of an `interface`. We need to do that to use the enum as keys.

If you add the following test ...

```typescript
testProcessProject(
  'generates type guards for properties with spaces in types instead of interfaces',
  {
    'test.ts': `
    /** @see {isFoo} ts-auto-guard:type-guard */
    export type Foo = {
      "foo 1": number,
      "bar 2": string
    }`,
  },
  {
    'test.guard.ts': `
    import { Foo } from "./test";

    export function isFoo(obj: any, _argumentName?: string): obj is Foo {
        return (
            (obj !== null && 
            typeof obj === "object" ||
            typeof obj === "function") &&
            typeof obj["foo 1"] === "number" &&
            typeof obj["bar 2"] === "string"
        )
    }`,
  }
)
```

(which is the same as [yours](https://github.com/rhys-vdw/ts-auto-guard/issues/123#issuecomment-749313446) but with a `type` instead on an `interface`)

... then the error occurs:

![type-interface](https://user-images.githubusercontent.com/26546651/105469761-00511e80-5c99-11eb-8229-b253170d74ef.png)

With this information, is it simple for you to fix the issue? Otherwise we'll have a deeper look.

**Comment by rhys-vdw** [comment]
> With this information, is it simple for you to fix the issue? Otherwise we'll have a deeper look.

Possibly, I don't typically work on this project directly anymore, but I will review and accept pull requests. The reason being that I rarely work in TS these days. If your PR is merged i will add you to collaborators, as I have with all other contributors.

**Comment by rhys-vdw** [comment]
@flixcheck Consider that this might actually be an upstream issue too. Why is it that these are represented differently by ts-morph? Presumably the values are coming out without the quotes that they have when they're object properties. e.g. `foo 1` instead of `"foo 1"`.

If there is nothing obviously silly going on is ts-auto-guard then this might be worth raising there.

We're also one major version behind on ts-morph, so this issue might even go away with an upgrade. 🤞

**Comment by chrisczach** [comment]
@rhys-vdw It looks like your suggested fix worked. I opened a PR.

**Comment by rhys-vdw** [comment]
Merged #124. I want to take a look into my thoughts [here](https://github.com/rhys-vdw/ts-auto-guard/issues/123#issuecomment-765862941) before closing the issue.

**Comment by flixcheck** [comment]
@rhys-vdw We added some tests (for the four combinations of `type` / `interface` + property names with spaces / with dashes) and can conclude that only the combination of a **type** property with a **dash** fails. We also increased the version of `ts-morph` and `@ts-morph/common` and fixed the resulting breaking changes, but it doesn't solve the issue.

I've attached our branch as zip.

[export-dashes-in-property-names.zip](https://github.com/rhys-vdw/ts-auto-guard/files/5932134/export-dashes-in-property-names.zip)

**Comment by rhys-vdw** [comment]
@flixcheck this is using the latest version? Can you open a PR?

**Comment by flixcheck** [comment]
@rhys-vdw Sure! Unfortunately I don't have the rights to push my branch:

```
Pushing to github.com:rhys-vdw/ts-auto-guard.git
ERROR: Permission to rhys-vdw/ts-auto-guard.git denied to flixcheck.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by rhys-vdw** [comment]
@flixcheck ah that's normal! In GitHub you can fork the project into your username's collection, create a branch there, then open a PR from this repository. :-)
