### ISSUE TITLE
Reduce code duplication for guards generated in other files

### ISSUE THREAD

**Issue by cameron-brown-future** [rhys-vdw/ts-auto-guard#131]
Ideally, if I have a type which uses another type, and both have type guards generated by this tool, it should avoid code duplication by importing its own generated type.

For instance, if I have:
```
// test-type.types.ts
/** @see {isTestType} ts-auto-guard:type-guard */
export interface TestType {
    someKey: string | number;
}

// test-type-list.types.ts
/** @see {isTestTypeList} ts-auto-guard:type-guard */
export type TestTypeList = TestType[];
```

then the expected output in `test-type-list.types.guard.ts` would be (something like):
```
import { TestTypeList } from 'test-type-list.types'
import { isTestType } from 'test-type.types.guard'

export function isTestTypeList(obj: any, _argumentName?: string): obj is TestTypeList {
    return (
        Array.isArray(obj) &&
        obj.every((e: any) =>
            isTestType(e) as boolean
        )
    )
}
```

This currently works if the type definitions are in the same file, but not in different files. I understand the difficulty of this, but if two conditions are met it should be relatively easy:

1. `test-type-list.types.ts` and `test-type.types.ts` are both passed into the same `ts-auto-guard` command call
2. They are listed in the correct order so that the predicate is defined first

In this case it should be called as: `ts-auto-guard test-type.types.ts test-type-list.types.ts`, that way we know about `isTestType` before we get to `isTestTypeList`, and they are both present in the same runthrough.

It would be nice if the tool would do this ordering & checking for us, but we can just rely on the user to make sure it's called correctly for now, maybe have a different issue for making this smarter.

**Comment by cameron-brown-future** [comment]
After reading through the code (and implementing a fix, one moment) I noticed that `ts-morph` actually re-orders the files sent in, which means we will need to sort the files into proper order during the process (condition 2. in the issue above)

**Comment by rhys-vdw** [comment]
Hey @cameron-brown-future sounds good! This is actually a feature that is meant to be supported already, not only if they're in the same file.
