### ISSUE TITLE
Multiple generation runs fail if a concrete file path is specified

### ISSUE THREAD

**Issue by SebastianKuehn** [rhys-vdw/ts-auto-guard#150]
Calling `ts-auto-guard --guard-file-name=type-guard src/Person.ts` with Version _1.0.0-alpha.25_ or _1.0.0-alpha.26_ fails the second time with:
```
UnhandledPromiseRejectionWarning: Error: Did you mean to provide the overwrite option? A source file already exists at the provided file path: /fullpath/to/src/Person.ts
```
Version _1.0.0-alpha.24_ works fine.

I think the problem is, that the guard files are not known to the project. In function `generate()` (line 944) the provided path (not the generated guard) is added to the project. Therefore `processProject()` doesn't find the generated guards in line 965:
```javascript
  // Delete previously generated guard.
  project
    .getSourceFiles(`./**/*.${guardFileName}.ts`)
    .forEach(sourceFile => deleteGuardFile(sourceFile))
```
and `deleteGuardFile()` is never called. The last assertion is a fact, as I checked it. It's not called in my setup.

I'm not providing a PR because I'm not sure how to fix the issue. Maybe extending `generate()` would do the trick:
```javascript
  const project = new Project({
    skipAddingFilesFromTsConfig: paths.length !== 0,
    tsConfigFilePath,
  })
  project.addSourceFilesAtPaths(paths)
  // also add generated guard files to the project
  project.addSourceFilesAtPaths(paths.map(path -> outFilePath(path, guardFileName)));
```

**Comment by rhys-vdw** [comment]
@SebastianKuehn hm... perhaps we should provide the overwrite option? Or at least allow it to be opt-in with a command line argument?

Either that or be smart and expand the list of supplies scripts to include any relative guard files. But I feel like ultimately that's the same thing.

I think we should also catch that error from ts-morph and report it a bit more gracefully.

Would you be interested in opening a PR with the relevant changes? Happy to answer any questions if you get stuck.

**Comment by rhys-vdw** [comment]
Hey, I just noticed your error:

> A source file already exists at the provided file path: /fullpath/to/src/Person.ts

This is not a guard file! Shouldn't it be `Person.type-guard.ts` with those arguments?

**Comment by SebastianKuehn** [comment]
@rhys-vdw Hi, sorry thats a typo from my side. The error contains a guard-file. I tried to be brief and messed up the file-part of the error message.

**Comment by rhys-vdw** [comment]
Thought that might be the case, all g. My original reply stands. 👍
