### ISSUE TITLE
For function types, should at least check if the property is indeed a function.

### ISSUE THREAD

**Issue by chomosuke** [rhys-vdw/ts-auto-guard#155]
If I have: 
```typescript
/** @see {isPerson} ts-auto-guard:type-guard */
export interface Person {
  age: (() => void);
}
```

It generates:
```typescript
/*
 * Generated type guards for "Person.ts".
 * WARNING: Do not manually change this file.
 */
import { Person } from "./Person";

export function isPerson(obj: any, _argumentName?: string): obj is Person {
    return (
        (obj !== null &&
            typeof obj === "object" ||
            typeof obj === "function") &&
        (obj.age !== null &&
            typeof obj.age === "object" ||
            typeof obj.age === "function")
    )
}
```

I'm not entirely sure if this is intentional. I know that in JavaScript it's not possible to check the runtime type of a function, but in my opinion we should at least do: 
```typescript
    return (
        (obj !== null &&
            typeof obj === "object" ||
            typeof obj === "function") &&
        (obj.age !== null &&
            typeof obj.age === "function")
    )
```

Also I think we should emit a warning (suppressible by comment) about how it's not actually possible to check JavaScript function type at runtime. In case someone is new to TypeScript/JavaScript.

**Comment by rhys-vdw** [comment]
Hey @chomosuke, thanks for the report. That seems sensible, happy to take a PR. Surprised this isn't already supported.

Bear in mind that function types can also have properties, so you'll possibly just need to augment the existing `objectCondition` (and possibly `objectTypeCondition`) to be distinguish.

If you do tackle it please add test coverage to show that it works.

**Comment by chomosuke** [comment]
Thanks @rhys-vdw. I am fairly busy at the moment so if anyone else want to tackle this they can. Otherwise I will probably start working on it in a month or so.
