### ISSUE TITLE
Unable to control processing

### ISSUE THREAD

**Issue by kernwig** [rhys-vdw/ts-auto-guard#169]
Processing a single file per the README: `$ ts-auto-guard ./my-project/Person.ts` simply displays "Done!" to the console and outputs no new files.

Only `$ ts-auto-guard --export-all` results in output, but it is confused by the barrel files and generates duplicates, and uses of guards in other files tries to import from the index.guard.ts the very guards defined in the importing file.

Using v1.0.0 with Typescript 4.0.8.

**Comment by kernwig** [comment]
I have to say that I love the approach of this tool. I've evaluated many input validation libraries and this is my favorite, but this bug makes it usable. I hope it's just a regression on the v1.0.0 release that can quickly be resolved. @rhys-vdw

**Comment by rhys-vdw** [comment]
This is probably a failure of the README rather than the library. The `--export-all` option will generate types for every single exported type in every file you pass, rather than the types you whitelist with jsdoc comments.

You probably don't want to use `--export-all` without passing a list of files (or honestly probably don't want to use it at all, I think it's better to whitelist and just process the whole project with a simple call to `ts-auto-guard`).

I've been meaning to fix the README for a while, it's a bit confusing.

**Comment by kernwig** [comment]
My types are to be generated from OpenAPI schema, which don't put the JsDoc on there.

`npx ts-auto-guard --export-all src/models/index.ts` to build a single guard file for all exported types _almost_ works. The `enum` types are imported from both "./index" and the files where they are defined; all other types are imported only from "./index". I'd prefer this way with all the generated code in one file, so that the root index.ts can just re-export this one file rather than doubling the lines. Small source files are great - generated code can be squished together.

Doing
`npx ts-auto-guard --export-all src/models/*.ts` creates both bad `index.guard.ts` and good individual guard files. So it is a workaround to do that and then delete `index.guard.ts`. It's sloppy, takes double the time, and have to re-export all these individual files, but is viable.

**Comment by rhys-vdw** [comment]
> My types are to be generated from OpenAPI schema, which don't put the JsDoc on there.

Understood!

>  The enum types are imported from both "./index" and the files where they are defined; all other types are imported only from "./index".

Oh... So it's creating more than one `.guard.ts` file even though you're including only one file in the arguments? If so that is definitely a bug.
