### ISSUE TITLE
Consider using ts-generator to simplify implementation

### ISSUE THREAD

**Issue by krzkaczor** [rhys-vdw/ts-auto-guard#22]
Hey!

I just stumbled upon your project, great idea! I worked on some code generation tools for typescript in the past and I realized that a lot of logic can be extracted to another tool: things like globbing files, watching, prettifying generated code etc. I have work in progress version here: https://github.com/krzkaczor/ts-generator 

Would you consider switching to `ts-generator` in the future? Currently, I work on migrating https://github.com/krzkaczor/TypeChain to use `ts-generator`. When it's done, its API should be more stable. I see that in your case finding source files to transpile is more complicating then just specifing glob pattern but I would be more than happy to tweak ts-generator API to match this use case.

What do you think?

**Comment by krzkaczor** [comment]
Yeah @rhys-vdw sorry about that, `ts-generator` is WIP, documentation and readme will appear in next days. 

I see that you use `ts-simple-ast`, I am not sure if it has nice API to work with strings instead of file system.

The premise of `ts-generator` is to allow to parse ANY file (not only ts) and generate based on that some TS files. In your project you focus explicitly on parsing TS files and I understand that using something like `ts-simple-ast` is just simpler. So I guess that using `ts-simple-ast` might be better idea for now. Thanks for your input, maybe in future there is a possibilty to integrate both tools.

**Comment by rhys-vdw** [comment]
> I see that you use ts-simple-ast, I am not sure if it has nice API to work with strings instead of file system.

Not sure exactly what you mean here, but it does have a "virtual file system" mode.

**Comment by rhys-vdw** [comment]
Closing for now, let me know when krzkaczor/ts-generator#8 is closed and I'll consider re-opening.
