### ISSUE TITLE
VS Code Integration

### ISSUE THREAD

**Issue by elliot-huffman** [rhys-vdw/ts-auto-guard#249]
I would like to propose an improvement to the IDE experience while developing this project.
The below changes allow developers to reduce the amount of steps they have to take to debug the project as well as reducing clutter in the search boxes by ignoring programmatically generated content such as the TSC's output and the `node_modules` folder.

I also noticed that the NPM ignore was not reflective of the current project and dev artifacts made their way into production builds on the NPM page.

And finally, I have updated the badges on the top of the readme, so it no longer has the greenkeeper migration logo and now shows off NPM and the Unit Test status.

Changes:
- Enable VS Code debugger integration (for both standard runs and unit tests)
- Migrate off of old `settings.json` to new `code-workspace` format.
- Add folder ignore to `node_modules` to reduce clutter in IDE
- Add `.js`/`.js.map` ignores to focus on the TypeScript in the search system
- Sync npm ignore to the project to ensure that only production artifacts are uploaded.
- Update readme badges

**Comment by rhys-vdw** [comment]
Closed by #250
