### ISSUE TITLE
Incorrect object check

### ISSUE THREAD

**Issue by rhys-vdw** [rhys-vdw/ts-auto-guard#60]
@keithlayne points out [on Gitter](https://gitter.im/Microsoft/TypeScript?at=5c3ec4e872cef52f6469be67):

> @rhys-vdw I don’t know if you did this on purpose, but some of your nested objects can error on null values like so in your gist:
> ```js
> > a = null
> null
> > typeof a === 'object' && typeof a.b === 'string'
> TypeError: Cannot read property 'b' of null
> ```

**Comment by keithlayne** [comment]
I approve. :P

**Comment by rhys-vdw** [comment]
hahahaha I was wondering if you'd get a notification @keithlayne. Thanks for the feedback. ;-)
