### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by 0xorial** [rhys-vdw/ts-auto-guard#67]
package.json contains some linux-specific code:

- chmod in 'build' command
- bunch of stuff in 'test' command

I am wondering if it could be improved somehow. I made some [workarounds](https://github.com/0xorial/ts-auto-guard/commit/3eda7f171e1650644cea83e0ab17bd1a944b9640#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L7), but I am not very happy about them...

**Comment by rhys-vdw** [comment]
@0xorial sorry for neglecting your issues here. I'm going to add you as a collaborator.
